services:
  - type: web
    name: student-attendance-backend
    env: docker
    region: oregon
    plan: free
    autoDeploy: true
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /docs
